# Generated by Django 2.2.2 on 2019-07-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20190717_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='autor',
            new_name='author',
        ),
    ]
