# Generated by Django 2.2.2 on 2019-07-17 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20190717_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 12, 50, 42, 44100, tzinfo=utc), verbose_name='date published'),
        ),
    ]
