# Generated by Django 2.2.2 on 2019-07-23 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190717_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 7, 57, 31, 152926, tzinfo=utc), verbose_name='date published'),
        ),
    ]
