# Generated by Django 3.0.3 on 2020-02-25 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_auto_20190723_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
