# Generated by Django 3.0.3 on 2020-03-02 16:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('knowledge', '0007_auto_20200225_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_update_tag_action', models.CharField(max_length=10)),
                ('last_update_tag_id', models.IntegerField()),
                ('last_update_memory_action', models.CharField(max_length=10)),
                ('last_update_memory_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
